from email.mime.text import MIMEText
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import datetime


class Ui_Dialog(object):

    def __init__(self):
        self.MailListesi = list()

    def setupUi(self, Dialog): # QtDesigner Otomatik Verisi
        Dialog.setObjectName("Dialog")
        Dialog.resize(796, 469)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Mail.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.eposta = QtWidgets.QLineEdit(self.widget_4)
        self.eposta.setObjectName("eposta")
        self.verticalLayout_5.addWidget(self.eposta)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.sifre = QtWidgets.QLineEdit(self.widget_5)
        self.sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifre.setObjectName("sifre")
        self.verticalLayout_4.addWidget(self.sifre)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.baslik = QtWidgets.QLineEdit(self.widget_6)
        self.baslik.setObjectName("baslik")
        self.verticalLayout_3.addWidget(self.baslik)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.mesaj = QtWidgets.QTextEdit(self.widget_7)
        self.mesaj.setObjectName("mesaj")
        self.verticalLayout_2.addWidget(self.mesaj)
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gonder = QtWidgets.QPushButton(self.widget_9)
        self.gonder.setObjectName("gonder")
        self.horizontalLayout_4.addWidget(self.gonder)
        self.vazgec = QtWidgets.QPushButton(self.widget_9)
        self.vazgec.setObjectName("vazgec")
        self.horizontalLayout_4.addWidget(self.vazgec)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.widget_7)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 12, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setStyleSheet("background-color:#186efd;border-bottom-left-radius: 25px;border-bottom-right-radius: 25px;")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_6.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout_6.addWidget(self.widget_10)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setContentsMargins(3, 0, 3, 3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setModelColumn(0)
        self.listWidget.setBatchSize(100)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_8.addWidget(self.listWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_8 = QtWidgets.QWidget(self.tab_2)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.widget_8)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.yeni_kisi_eposta = QtWidgets.QLineEdit(self.widget_8)
        self.yeni_kisi_eposta.setObjectName("yeni_kisi_eposta")
        self.verticalLayout_9.addWidget(self.yeni_kisi_eposta)
        self.label_9 = QtWidgets.QLabel(self.widget_8)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.yeni_kisi_adsoyad = QtWidgets.QLineEdit(self.widget_8)
        self.yeni_kisi_adsoyad.setObjectName("yeni_kisi_adsoyad")
        self.verticalLayout_9.addWidget(self.yeni_kisi_adsoyad)
        self.verticalLayout_10.addWidget(self.widget_8)
        self.widget_11 = QtWidgets.QWidget(self.tab_2)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yeni_kisi_ekle = QtWidgets.QPushButton(self.widget_11)
        self.yeni_kisi_ekle.setObjectName("yeni_kisi_ekle")
        self.horizontalLayout_2.addWidget(self.yeni_kisi_ekle)
        self.sifirla = QtWidgets.QPushButton(self.widget_11)
        self.sifirla.setObjectName("sifirla")
        self.horizontalLayout_2.addWidget(self.sifirla)
        self.verticalLayout_10.addWidget(self.widget_11)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.verticalLayout_6.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.gonder.clicked.connect(self.gonder_button)
        self.vazgec.clicked.connect(QtWidgets.qApp.quit)
        self.sifirla.clicked.connect(self.temizle)
        self.yeni_kisi_ekle.clicked.connect(self.yeni_kisi_eklendi_buton)
        self.liste_yazici()

    def retranslateUi(self, Dialog): # QtDesigner Otomatik Verisi
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BotMail - Designed By Cemre Acar"))
        self.label.setText(_translate("Dialog", "E-Posta"))
        self.label_2.setText(_translate("Dialog", "Şifre"))
        self.label_3.setText(_translate("Dialog", "Başlık"))
        self.label_4.setText(_translate("Dialog", "Mesajınız"))
        self.gonder.setText(_translate("Dialog", "Tüm Kişilere Gönder"))
        self.vazgec.setText(_translate("Dialog", "Vazgeç"))
        self.label_5.setText(_translate("Dialog", "BotMail v1.0 2019 - Cemre Acar"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#FFF;\">BotMail</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#ffffff;\">Designed By Cemre Acar</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Gönderilecek Kişiler"))
        self.label_8.setText(_translate("Dialog", "Yeni Kişinin E-Postası"))
        self.label_9.setText(_translate("Dialog", "Yeni Kişinin Adı-Soyadı"))
        self.yeni_kisi_ekle.setText(_translate("Dialog", "Yeni Kişi Ekle"))
        self.sifirla.setText(_translate("Dialog", "Sıfırla"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Yeni Kişi Ekle"))

    def basarili(self,kisi_sayisi): # Herşeyin Yolunda Olduğunu Gösteren MessageBox Üretimi
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)

        msg.setText("BotMail Bilgilendirme Mesajı")
        msg.setInformativeText(str(kisi_sayisi)+" Mail Başarıyla Gönderildi")
        msg.setWindowTitle("BotMail Bilgilendirme Mesajı")
        msg.setDetailedText("Gönderen : "+self.eposta.text()+"\nZaman Dilimi : "+str(datetime.datetime.now().time()))
        msg.setStandardButtons(QMessageBox.Ok)
        retval = msg.exec_()

        self.eposta.clear()
        self.sifre.clear()
        self.baslik.clear()
        self.mesaj.clear()

    def yeni_kisi_basarili(self): # Herşeyin Yolunda Olduğunu Gösteren MessageBox Üretimi
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)

        msg.setText("BotMail Bilgilendirme Mesajı")
        msg.setInformativeText("Yeni Kişi Başarıyla Eklendi !")
        msg.setWindowTitle("BotMail Bilgilendirme Mesajı")
        msg.setStandardButtons(QMessageBox.Ok)
        retval = msg.exec_()

        self.yeni_kisi_adsoyad.clear()
        self.yeni_kisi_eposta.clear()

    def basarisiz(self): # Bir Hata Olduğunu Gösteren MessageBox Üretimi
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)

        msg.setText("BotMail Bilgilendirme Mesajı")
        msg.setInformativeText("Mail Gönderme İşlemi Başarısız Oldu !")
        msg.setWindowTitle("BotMail Bilgilendirme Mesajı")
        msg.setDetailedText("İnternet Bağlantınızı , E-Posta & Şifre Uyumunu ve Gönderilen E-Postanın Doğruluğunu Kontrol Ediniz ! Bazı Kişilere Mailleriniz Gönderilmiş Olabilir. Lütfen Kişilerinizin Doğruluğunu Kontrol Edin !")
        msg.setStandardButtons(QMessageBox.Ok)
        retval = msg.exec_()

    def yeni_kisi_basarisiz(self): # Bir Hata Olduğunu Gösteren MessageBox Üretimi
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)

        msg.setText("BotMail Bilgilendirme Mesajı")
        msg.setInformativeText("Yeni Kişi Ekleme İşlemi Başarısız Oldu !")
        msg.setWindowTitle("BotMail Bilgilendirme Mesajı")
        msg.setDetailedText("İnternet Bağlantınızı Kontrol Ediniz !")
        msg.setStandardButtons(QMessageBox.Ok)
        retval = msg.exec_()

    def yeni_kisi_empty(self): # Bir Hata Olduğunu Gösteren MessageBox Üretimi
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)

        msg.setText("BotMail Bilgilendirme Mesajı")
        msg.setInformativeText("Yeni Kişi Ekleme İşlemi Başarısız Oldu !")
        msg.setWindowTitle("BotMail Bilgilendirme Mesajı")
        msg.setDetailedText("Ad Soyad veya E-Posta Boş Girilemez !")
        msg.setStandardButtons(QMessageBox.Ok)
        retval = msg.exec_()

    def okuma_basarisiz(self): # Text Dosyası Okunurken Bir Hata Olduğunu Gösteren MessageBox Üretimi
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)

        msg.setText("BotMail Bilgilendirme Mesajı")
        msg.setInformativeText("Verilerin Tutulduğu Dosya Okunurken Bir Hata Oluştu !")
        msg.setWindowTitle("BotMail Bilgilendirme Mesajı")
        msg.setDetailedText("Dosyanızda Bir Bozukluk Olup Olmadığını Kontrol Edin !")
        msg.setStandardButtons(QMessageBox.Ok)
        retval = msg.exec_()

    def temizle(self): # Yeni Kişi Ekleme Form Temizleme Fonksiyonu
        self.yeni_kisi_eposta.clear()
        self.yeni_kisi_adsoyad.clear()
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)

    def yeni_kisi_eklendi_buton(self): # Yeni Kişi Ekleme Fonksiyonu
        ekle = open("BotMail_System/mail_list.txt", "a")
        eposta = self.yeni_kisi_eposta.text()
        adsoyad = self.yeni_kisi_adsoyad.text()
        if eposta or adsoyad != "":
            try:
                ekle.write(eposta+","+adsoyad+",\n")
                self.yeni_kisi_basarili()
                self.listWidget.addItem(eposta+" "+adsoyad)
                self.tabWidget.setCurrentIndex(0)
            except:
                self.yeni_kisi_basarisiz()

        else:
            self.yeni_kisi_empty()

    def postala(self): # E-Postayı Gönderen Fonksiyon
        file = open("BotMail_System/mail_list.txt", "r")
        for i in file.readlines():
            self.MailListesi.append(i.split(","))

        for x in range(len(self.MailListesi)):
            self.islemler(self.eposta.text(), self.MailListesi[int(x)][0], self.MailListesi[int(x)][1], self.sifre.text(),self.baslik.text() , self.mesaj.toPlainText())

    def gonder_button(self): # Gönder Butonu Fonksiyonu
        try:
            self.postala()
            self.basarili(len(self.MailListesi))
        except:
            self.basarisiz()

    def liste_yazici(self): # ListWidget'a Verileri Yazdıran Fonksiyon
        file = open("BotMail_System/mail_list.txt", "r")
        for i in file.readlines():
            self.MailListesi.append(i.split(","))
            self.listWidget.clear()
            try:
                for s in range(len(self.MailListesi)):
                    self.listWidget.addItem(self.MailListesi[s][0]+" "+self.MailListesi[s][1])
            except:
                self.okuma_basarisiz()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
